### ISSUE TITLE
npmにpublishしてほしい

### ISSUE THREAD

**Issue by vvakame** [kongou-ae/redpen-validator#48]
以下のようなユースケースです。
1. 複数人で本を書き始める e.g. https://github.com/TechBooster/C89-FirstStepReVIEW-v2
2. 代表者1名が環境を整備し、他の人は書くだけ
3. タスクランナーとしてnpm scriptとgruntなどを使っているためNode.js環境はみんなある(他の著者もnpm経由でPDFを生成する
4. 各執筆者の環境で `npm install` と `npm run pdf` などが実行される

この中で、npmに本validatorが提供されているとgit submoduleなどを使わずに済むので楽ができるなぁ…と考えています。

**Comment by kongou-ae** [comment]
@vvakame 面白そうなので、npmの勉強ということで対応を検討します。

上記のユースケースについて1点教えてください。RedPen自体がnpmでインストールできない以上、本validatorがnpmに対応するメリットは限定的だと思いました。RedPen自体はどのように各執筆者の環境にインストールするのでしょうか。

**Comment by vvakame** [comment]
わりとMac+HomeBrew決め打ちで `brew install redpen` してね！で済ませてます。
使っているドキュメントシステムがRe:VIEWなのでrubyとかも入れる必要があり地味に大変です…。
モノ的にはMavenCentralとかからjarなり落としてくれば良い気もします。

**Comment by kongou-ae** [comment]
なるほど。RedPenが`brew install redpen`でインストールできるのに、本Validatorがgit cloneしなきゃいけないのは手間ですね。npm挑戦してみます。

**Comment by kongou-ae** [comment]
npmは公開するパッケージのURLにアカウント名が付かないので、[redpen-validator-easy-to-read-japanese-document](https://www.npmjs.com/package/redpen-validator-easy-to-read-japanese-document)というパッケージ名で公開しました。

当面の間、npm publishは手動になります。別途CircleCIによる自動publishを検討します。

**Comment by vvakame** [comment]
ありがとうございます！
時間を見つけて試してみます。
